# fly.toml file generated for dota-coach on 2023-03-26T19:13:54-04:00

app = "dota-coach"
primary_region = "yyz"

[env]
  HOST = "0.0.0.0"
  PORT = "8080"
  SERVER_URL = "http://dota-coach.fly.dev"
  NODE_ENV = "production"
  PERSISTENCE_DATA_PATH = "./data/data.json"

[http_service]
  internal_port = 8080

[mounts]
source="dota_coach_volume"
destination="/data"