process.env.DISCORD_BOT_TOKEN = "test_DISCORD_BOT_TOKEN";
process.env.MIXPANEL_PROJECT_TOKEN = "test_MIXPANEL_PROJECT_TOKEN";
process.env.PERSISTENCE_DATA_PATH = "test_PERSISTENCE_DATA_PATH";
process.env.STUDENT_ID_HASH_PRIVATE_KEY = "test_STUDENT_ID_HASH_PRIVATE_KEY";
